apiVersion: batch/v1
kind: CronJob
metadata:
  name: metric-app
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: metric-app
            image: scloudacr.azurecr.io/metric-app:latest
            imagePullPolicy: Always
          restartPolicy: OnFailure