apiVersion: v1
kind: Service
metadata:
  name: healthprobe-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
spec:
  selector:
    name: healthprobe-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer