apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-log
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-log